<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>C:\Users\Tom Pipe\Documents\Hexadigital\Code\Umbraco\Umbraco-CMS\src\Umbraco.Tests\AttemptTests.cs</title>
    <script type="text/javascript" src="../js/dotcover.sourceview.js"></script>
    <link rel="stylesheet" type="text/css" href="../css/dotcover.report.css" />
  </head>
  <body>
    <pre id="content" class="source-code">
using System;
using NUnit.Framework;
using Umbraco.Core;

namespace Umbraco.Tests
{
    [TestFixture]
    public class AttemptTests
    {
        [Test]
        public void Chained_Attempts()
        {
            Attempt.Try(Attempt.Succeed(&quot;success!&quot;),
                s =&gt; Assert.AreEqual(&quot;success!&quot;, s),
                exception =&gt; Assert.Fail(&quot;Should have been successful.&quot;))

                // previous one was a success so that one SHOULD NOT run
                // and report success
                .OnFailure(() =&gt; Attempt.Succeed(123),
                    i =&gt; Assert.Fail(&quot;The previous attempt was successful!&quot;),
                    exception =&gt; Assert.Fail(&quot;The previous attempt was successful!&quot;))

                // previous one did not run, last run was a success so that one SHOULD run
                // and report failure
                .OnSuccess(() =&gt; Attempt&lt;double&gt;.Fail(new Exception(&quot;Failed!&quot;)),
                    d =&gt; Assert.Fail(&quot;Should have failed.&quot;),
                    exception =&gt; Assert.AreEqual(&quot;Failed!&quot;, exception.Message))

                // previous one did run and was a failure so that one SHOULD NOT run
                .OnSuccess(() =&gt; Attempt.Succeed(987),
                    i =&gt; Assert.Fail(&quot;The previous attempt failed!&quot;),
                    exception =&gt; Assert.Fail(&quot;The previous attempt failed!&quot;))

                // previous one did not run, last run was a failure so that one SHOULD run
                // then why does it run?
                .OnFailure(() =&gt; Attempt.Succeed(&quot;finished&quot;),
                    i =&gt; Assert.AreEqual(&quot;finished&quot;, i),
                    exception =&gt; Assert.Fail(&quot;Should have been successful.&quot;));
        }

        [Test]
        public void AttemptIf()
        {
            // just making sure that it is ok to use TryParse as a condition

            int value;
            var attempt = Attempt.If(int.TryParse(&quot;1234&quot;, out value), value);
            Assert.IsTrue(attempt.Success);
            Assert.AreEqual(1234, attempt.Result);

            attempt = Attempt.If(int.TryParse(&quot;12xxx34&quot;, out value), value);
            Assert.IsFalse(attempt.Success);
        }
    }
}

    </pre>
    <script type="text/javascript">
      highlightRanges([[12,9,12,10,1],[13,13,14,22,1],[14,22,14,52,1],[14,52,15,30,1],[15,30,15,73,0],[15,73,19,34,1],[19,34,19,54,0],[19,54,20,26,1],[20,26,20,77,0],[20,77,21,34,1],[21,34,21,85,0],[21,85,25,34,1],[25,34,25,80,1],[25,80,26,26,1],[26,26,26,60,0],[26,60,27,34,1],[27,34,27,79,1],[27,79,30,34,1],[30,34,30,54,0],[30,54,31,26,1],[31,26,31,69,0],[31,69,32,34,1],[32,34,32,77,0],[32,77,36,34,1],[36,34,36,61,1],[36,61,37,26,1],[37,26,37,56,1],[37,56,38,34,1],[38,34,38,77,0],[38,77,38,79,1],[13,13,38,79,1],[39,9,39,10,1],[43,9,43,10,1],[47,13,47,78,1],[48,13,48,44,1],[49,13,49,51,1],[51,13,51,77,1],[52,13,52,45,1],[53,9,53,10,1]]);
    </script>
  </body>
</html>